default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  # username: postgres
  # password: <%= ENV['PG_PASSWORD'] %>
  database: Budget_app_development

test:
  <<: *default
  # username: postgres
  # password: <%= ENV['PG_PASSWORD'] %>
  database: Budget_app_test

production:
  <<: *default
  url: <% ENV["DATABASE_URL"]%>
