default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>
  port: 5432
  host: localhost

development:
  <<: *default
  database: Budget_app_development

test:
  <<: *default
  database: Budget_app_test

production:
  <<: *default
  url: <% ENV["DATABASE_URL"]%>
